spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: public
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://localhost:5432/MMD
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

server:
  port: 8080

